### PR TITLE
`dt_squash` anonymous functions

### LINKED ISSUE #362: Better handling of anonymous functions by internal `capture_dots()`
``` r
library(dplyr, w = FALSE)
library(dtplyr)
library(data.table, w = FALSE)

df <- data.table(x = list(1, 1, 1))

df %>%
  mutate(z = sapply(x, function(.x) .x + n()))
#> Error in `n()`:
#> ! Must be used inside dplyr verbs.
```

### PR DESCRIPTION
**Pull request by markfairbanks**
Closes #362

### CODE REVIEW

**Review by eutwt — APPROVED** [review]
LGTM

**Comment by eutwt** [comment]
This fixes the issue outside of across, but make me realize I didn't handle #288 right, because anonymous functions in `across` don't get dplyr verbs translated

```r
lazy_dt(tibble(y = 1)) %>% 
  mutate(across(y, function(x) x + n()))
```

**Comment by markfairbanks** [comment]
Ah for some reason I assumed that `across()` would be using the same `dt_squash()` path but looks like it's different.

Might be easier to merge this one and deal with the `across()` issue separately. That work for you @eutwt?

**Comment by eutwt** [comment]
Yeah I think that makes sense

**Pull request merged**
