### PR TITLE
`add_count` function

### LINKED ISSUE #298: add_count does not work properly
When using `add_count` and `filter` together,  `add_count` DOES NOT drop the group variable. 

```r
library(tidyverse)
library(dtplyr)

dat <- lazy_dt(iris)

dat %>% 
  add_count(Species) %>% 
  filter(Sepal.Length >= 5) %>% 
  collect() %>% 
  head(1)
```

Notice that the result has a group variable `Species `.

```r
# A tibble: 1 × 6
# Groups:   Species [1]
  Sepal.Length Sepal.Width Petal.Length Petal.Width Species     n
         <dbl>       <dbl>        <dbl>       <dbl> <fct>   <int>
1          5.1         3.5          1.4         0.2 setosa     50
```

However, the following code works fine.

```r
dat %>% 
  group_by(Species) %>% 
  mutate(n = n()) %>% 
  ungroup() %>%
  filter(Sepal.Length >= 5) %>% 
  collect() %>% 
  head(1)
```

```r
# A tibble: 1 × 6
  Sepal.Length Sepal.Width Petal.Length Petal.Width Species     n
         <dbl>       <dbl>        <dbl>       <dbl> <fct>   <int>
1          5.1         3.5          1.4         0.2 setosa     50
```

### PR DESCRIPTION
**Pull request by eutwt**
closes #298 

Issue:
The output here should not be grouped, but it is:

``` r
library(dplyr, warn.conflicts = FALSE)
library(dtplyr)

lazy_dt(data.frame(a = 1)) %>% 
  add_count(a) 
#> Source: local data table [1 x 2]
#> Groups: a
#> Call:   copy(`_DT1`)[, `:=`(n = .N), by = .(a)]
#> 
#>       a     n
#>   <dbl> <int>
#> 1     1     1
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
```

<sup>Created on 2021-09-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

If `dplyr:::add_count.default` had one more line at the end to regroup the output with `group_by` this PR would be unnecessary. Not sure if it's better for dtplyr and dbplyr to handle this themselves, opening this PR in case.

### CODE REVIEW

**Comment by hadley** [comment]
@eutwt can I get your email address please? I need to ask you a quick question.

**Comment by eutwt** [comment]
> @eutwt can I get your email address please? I need to ask you a quick question.

Remove the all the "z"s from ryazndiczkzerson@fastmail.com (sorry, trying to avoid spam)

**Comment by hadley** [comment]
@eutwt thanks just emailed you 😄

**Comment by hadley** [comment]
@eutwt just wanted to check that you got the email — I don't want to rush any decisions, but I'd really like to get dtplyr out soon, since it's blocking the dplyr release, and ideally I'd like to announce all the new authors at once 😄

**Comment by eutwt** [comment]
Apologies for the late response, I've submitted the PR

**Comment by markfairbanks** [comment]
> If dplyr:::add_count.default had one more line at the end to regroup the output with group_by this PR would be unnecessary. Not sure if it's better for dtplyr and dbplyr to handle this themselves, opening this PR in case.

@eutwt We can just make the addition here. Can you add a NEWS bullet?

**Pull request merged**
