### PR TITLE
Fast `select()`

### LINKED ISSUE #367: Fast `select()`
Currently `select()` always takes a deep copy. We can instead drop columns by reference if an implicit or explicit copy has already occurred in the pipe chain.

Waiting on #366 

``` r
library(dplyr, warn.conflicts = FALSE)
library(dtplyr)

df <- lazy_dt(tibble(x = 1, y = 2))

# Old
df %>%
  mutate(z = 3) %>%
  select(x, z)
#> Source: local data table [1 x 2]
#> Call:   copy(`_DT1`)[, `:=`(z = 3)][, .(x, z)]
#> 
#>       x     z
#>   <dbl> <dbl>
#> 1     1     3
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results

# New
remove_vars <- dtplyr:::remove_vars

df %>%
  mutate(z = 3) %>%
  remove_vars("y")
#> Source: local data table [1 x 2]
#> Call:   copy(`_DT1`)[, `:=`(z = 3)][, `:=`("y", NULL)]
#> 
#>       x     z
#>   <dbl> <dbl>
#> 1     1     3
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
```

### PR DESCRIPTION
**Pull request by markfairbanks**
Closes #367

Overview:
* Drop columns by reference in `select()` by using `remove_vars()` when:
  * Data has been copied (implicitly or explicitly)
  * There is no renaming in the select statement
  * The selection can't be combined with a prior `i` step. Ex: `dt[x < 7, .(x, y)]`
* Remove usage of `remove_vars()` from other functions and use `select()` for consistency

### CODE REVIEW

**Comment by markfairbanks** [comment]
Note: I'll update this to use the `is_copied()` util once #374 is merged

**Review by eutwt — CHANGES_REQUESTED** [review]
I think the change looks good, but none of the select tests check for this method. Maybe just duplicate the existing tests with the data having `needs_copy = TRUE` set manually? i.e. could add below to test-step-subset-select.R. Up to you how exactly to do it, but seems like this method should be in the tests somehow.

<details>
  <summary>tests</summary>
  
```r
### When data is copied (possibly using DT[, col := NULL] method)

test_that("copied data: can select variables", {
  dt <- lazy_dt(data.table(x = 1, y = 1, z = 1), "DT")
  dt$needs_copy <- TRUE

  expect_equal(
    dt %>% select(-z) %>% show_query(),
    expr(copy(DT)[, `:=`("z", NULL)])
  )

  expect_equal(
    dt %>% select(y, x) %>% show_query(),
    expr(setcolorder(copy(DT)[, `:=`("z", NULL)], c("y", "x")))
  )

  expect_equal(
    dt %>% select(a = x, y) %>% show_query(),
    expr(DT[, .(a = x, y)])
  )
})

test_that("copied data: can merge iff j-generating call comes after i", {
  dt <- lazy_dt(data.table(x = 1, y = 1, z = 1), "DT")
  dt$needs_copy <- TRUE

  expect_equal(
    dt %>% filter(x > 1) %>% select(y) %>% show_query(),
    expr(copy(DT)[x > 1, .(y)])
  )
  expect_equal(
    dt %>% select(x = y) %>% filter(x > 1) %>% show_query(),
    expr(copy(DT)[, .(x = y)][x > 1])
  )

})

test_that("copied data: renames grouping vars", {
  dt <- lazy_dt(data.table(x = 1, y = 1, z = 1))
  gt <- group_by(dt, x)
  gt$needs_copy <- TRUE

  expect_equal(select(gt, y = x)$groups, "y")
})

test_that("copied data: empty select returns no columns", {
  dt <- data.table(x = 1, y = 1, z = 1)
  lz <- lazy_dt(dt, "DT")
  lz$needs_copy <- TRUE
  expect_equal(
    lz %>% select() %>% collect(),
    tibble()
  )

  # unless it's grouped
  skip_if(utils::packageVersion("rlang") < "0.5.0")
  expect_snapshot(out <- lz %>% group_by(x) %>% select())
  expect_equal(
    out %>% collect(),
    group_by(tibble(x = 1), x)
  )
})

test_that("copied data: vars set correctly", {
  dt <- lazy_dt(data.frame(x = 1:3, y = 1:3))
  dt$needs_copy <- TRUE
  expect_equal(dt %>% select(a = x, y) %>% .$vars, c("a", "y"))
  expect_equal(dt %>% select(y) %>% .$vars, c("y"))
})

test_that("copied data: only add step if necessary", {
  dt <- lazy_dt(data.frame(x = 1:3, y = 1:3), "DT")
  dt$needs_copy <- TRUE
  expect_equal(dt %>% select(everything()), dt)
  expect_equal(dt %>% select(x, y), dt)
})
```

</details>

**Review by mgirlich — APPROVED** [review]

**Comment by markfairbanks** [comment]
@eutwt I'm in the process of adding tests. I see one of the tests uses `skip_if(utils::packageVersion("rlang") < "0.5.0")` - is there a reason we would need this? Both dplyr and dtplyr depend on `rlang >= 1.0.0`

**Comment by eutwt** [comment]
Welp. I thought the two commits above would fix the snapshot errors. Sorry about that. I guess I can revert those two commits and then just edit the snapshot to match the "chr_as_locations" error. But I don't understand why it would have that in the error message, it looks to be using the latest version of rlang, vctrs, and testthat.

**Comment by eutwt** [comment]
I guess using `error_call = .call` in `eval_select` didn't work because that was only added in the development version, which I now see in [the tidyselect news.md](https://github.com/r-lib/tidyselect/blob/main/NEWS.md). Sorry for crudding up the PR with the commits.

**Review by eutwt — APPROVED** [review]

**Comment by markfairbanks** [comment]
> I guess using error_call = .call in eval_select didn't work because that was only added in the development version, which I now see in [the tidyselect news.md](https://github.com/r-lib/tidyselect/blob/main/NEWS.md). Sorry for crudding up the PR with the commits.

No worries, worth a try. Btw it looks like `eval_select(error_call = )` exists in the CRAN version. Not sure what was causing the error in the checks. I'm going to merge this for now - maybe we can give it a try in another PR.

**Pull request merged**
