### PR TITLE
By early grouping fix

### LINKED ISSUE #439: Bug in `.by` argument of `mutate()` after selecting columns
Errors occur if `.by` is specified when `mutate()` after selecting columns.
In the following example, a data frame with 3 columns (`Species`, `Sepal.Length`, `Sepal.Length_mean`) should be output.

The second reprex without `select()` does not cause an error.

``` r
library(tidyverse)
library(dtplyr)

iris %>%
  lazy_dt() %>%
  select(Species, Sepal.Length) %>%
  mutate(Sepal.Length_mean = mean(Sepal.Length),
         .by = Species) %>%
  collect() %>%
  head()
#> Error in `as_tibble()`:
#> ! Column name `Species` must not be duplicated.
#> Use `.name_repair` to specify repair.
#> Caused by error in `repaired_names()`:
#> ! Names must be unique.
#> ✖ These names are duplicated:
#>   * "Species" at locations 1 and 2.
#> Backtrace:
#>      ▆
#>   1. ├─... %>% head()
#>   2. ├─utils::head(.)
#>   3. ├─dplyr::collect(.)
#>   4. └─dtplyr:::collect.dtplyr_step(.)
#>   5.   ├─tibble::as_tibble(x)
#>   6.   └─dtplyr:::as_tibble.dtplyr_step(x)
#>   7.     ├─tibble::as_tibble(dt_eval(x), .name_repair = .name_repair)
#>   8.     └─tibble:::as_tibble.data.frame(dt_eval(x), .name_repair = .name_repair)
#>   9.       └─tibble:::lst_to_tibble(unclass(x), .rows, .name_repair)
#>  10.         └─tibble:::set_repaired_names(...)
#>  11.           └─tibble:::repaired_names(...)
#>  12.             ├─tibble:::subclass_name_repair_errors(...)
#>  13.             │ └─base::withCallingHandlers(...)
#>  14.             └─vctrs::vec_as_names(...)
#>  15.               └─vctrs (local) `<fn>`()
#>  16.                 └─vctrs:::validate_unique(names = names, arg = arg, call = call)
#>  17.                   └─vctrs:::stop_names_must_be_unique(names, arg, call = call)
#>  18.                     └─vctrs:::stop_names(...)
#>  19.                       └─vctrs:::stop_vctrs(...)
#>  20.                         └─rlang::abort(message, class = c(class, "vctrs_error"), ..., call = call)
```

<sup>Created on 2023-07-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

``` r
library(tidyverse)
library(dtplyr)

iris %>%
  lazy_dt() %>%
  mutate(Sepal.Length_mean = mean(Sepal.Length),
         .by = Species) %>%
  collect() %>%
  head()
#> # A tibble: 6 × 6
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species Sepal.Length_mean
#>          <dbl>       <dbl>        <dbl>       <dbl> <fct>               <dbl>
#> 1          5.1         3.5          1.4         0.2 setosa               5.01
#> 2          4.9         3            1.4         0.2 setosa               5.01
#> 3          4.7         3.2          1.3         0.2 setosa               5.01
#> 4          4.6         3.1          1.5         0.2 setosa               5.01
#> 5          5           3.6          1.4         0.2 setosa               5.01
#> 6          5.4         3.9          1.7         0.4 setosa               5.01
```

<sup>Created on 2023-07-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### PR DESCRIPTION
**Pull request by eutwt**
Closes #439

Leaving in draft status for now because I don't understand why this fixes the issue

### CODE REVIEW

**Comment by markfairbanks** [comment]
So I have no idea why this is occurring (or why `step_group()` fixes it), but FYI this also happens with other functions.

``` r
pacman::p_load(dtplyr, dplyr)

iris %>%
  lazy_dt() %>%
  select(Species, Sepal.Length) %>%
  filter(Sepal.Length <= mean(Sepal.Length),
         .by = Species)
#> Source: local data table [82 x 3]
#> Call:
#>   _DT2 <- `_DT1`[, .(Species, Sepal.Length), keyby = .(Species)]
#>   `_DT2`[`_DT2`[, .I[Sepal.Length <= mean(Sepal.Length)], by = .(Species)]$V1]
#> 
#>   Species Species Sepal.Length
#>   <fct>   <fct>          <dbl>
#> 1 setosa  setosa           4.9
#> 2 setosa  setosa           4.7
#> 3 setosa  setosa           4.6
#> 4 setosa  setosa           5  
#> 5 setosa  setosa           4.6
#> 6 setosa  setosa           5  
#> # ℹ 76 more rows
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
```

**Comment by markfairbanks** [comment]
This has to be something weird about R's copy-on-modify semantics, but it's way over my head what could be happening. It makes no sense to me that it would alter the object for the prior step.

**Comment by markfairbanks** [comment]
So basically the error is caused by something weird in R's copy-on-modify semantics. As far as I know, it _shouldn't_ be altering the object for the prior step when using `parent$group <-`, but it does. No idea why.

 `step_group()` fixes it because it uses `new_step()`, which is creating a "new" `dtplyr_step` object from scratch. So the weird copy-on-modify behavior is skipped.

That being sad - I think we just need to switch out our uses of `object$group` throughout the code base to ensure we're not messing this up in other places.

**Comment by eutwt** [comment]
That makes sense. Closing this PR since there's a larger issue

**Comment by markfairbanks** [comment]
Ah yep I see what you mean. The issue is still a bit over my head though 😅

I might have some time to revisit in the future, but hopefully #445 covers what we need for now.

**Comment by eutwt** [comment]
Yeah, the fix is the same regardless

**Comment by markfairbanks** [comment]
Ah great, good to know.

**Pull request closed without merging**
