### PR TITLE
Remove `data.table` methods

### LINKED ISSUE #312: S3 method overloading on namespace load
I started to use dtplyr but there is a behaviour I cannot understand - I'm afraid I do not know whether it's a beginners' misunderstanding or a bug, but I cannot find any documentation about this so I decided to post it here.

In essence, creating a lazy data.table alters the original variable, as in this minimal reprex:
```r
# defining a dummy data table
x <- data.table::data.table(a=1:5, b=letters[1:5])

# operation (1): applying a mutate statement to it - this works fine
x |> dplyr::mutate(c=paste(a,b))

# creating the corresponding lazy data table
x2 <- dtplyr::lazy_dt(x)

# applying dplyr::mutate to x2 and obtaining it with as.data.table works fine
#    and returns a data.table object.
x2 |> dplyr::mutate(c=paste(a,b)) |> data.table::as.data.table()

# but running again operation (1) seems to re-create a dtplyr object,
#    leading to a different result than in the first call above.
class(x |> dplyr::mutate(c=paste(a,b)))                                                                                                                                                                          
# [1] "dtplyr_step_mutate" "dtplyr_step"
```

Note that also after assigning x2 result into a new variable, applying any dplyr verb re-creates a dtplyr object:
```r
y <- x2 |> dplyr::mutate(c=paste(a,b)) |> data.table::as.data.table()
y
#     a b   c
# 1: 1 a 1 a
# 2: 2 b 2 b
# 3: 3 c 3 c
# 4: 4 d 4 d
# 5: 5 e 5 e

class(y |> dplyr::mutate(d=0))
# [1] "dtplyr_step_mutate" "dtplyr_step"
```

I did not expect either of these two behaviours. Is it intended that any object, once converted to a lazy data table, cannot anymore fully loose the lazy property?

Is there a way to force an object to be a normal data.table?

Or is there something fundamental I am missing, which might be documented somewhere?

I am using the following versions:
- R: 4.1.1
- dplyr: 1.0.7
- dtplyr: 1.1.0
- data.table: 1.14.2

### PR DESCRIPTION
**Pull request by markfairbanks**
Closes #312

### CODE REVIEW

**Comment by hadley** [comment]
rFIA failure:

```
 > area(db = fiaRI_mr)
  Error in `dplyr::select()`:
  ! Can't subset columns that don't exist.
  ✖ Column `fad_mean` doesn't exist.
  Backtrace:
       ▆
    1. ├─rFIA::area(db = fiaRI_mr)
    2. │ └─... %>% dplyr::select(YEAR, fad_mean, fad_var)
    3. ├─dplyr::select(., YEAR, fad_mean, fad_var)
    4. └─dplyr:::select.data.frame(., YEAR, fad_mean, fad_var)
    5.   ├─dplyr:::tidyselect_fix_call(...)
    6.   │ └─base::withCallingHandlers(...)
    7.   └─tidyselect::eval_select(expr(c(...)), .data)
    8.     └─tidyselect:::eval_select_impl(...)
    9.       ├─tidyselect:::with_subscript_errors(...)
   10.       │ ├─base::tryCatch(...)
   11.       │ │ └─base (local) tryCatchList(expr, classes, parentenv, handlers)
   12.       │ │   └─base (local) tryCatchOne(expr, names, parentenv, handlers[[1L]])
   13.       │ │     └─base (local) doTryCatch(return(expr), name, parentenv, handler)
   14.       │ └─tidyselect:::with_entraced_errors(expr)
   15.       │   └─rlang::try_fetch(...)
   16.       │     └─base::withCallingHandlers(...)
   17.       └─tidyselect:::vars_select_eval(...)
   18.         └─tidyselect:::walk_data_tree(expr, data_mask, context_mask, error_call)
   19.           └─tidyselect:::eval_c(expr, data_mask, context_mask)
   20.             └─tidyselect:::reduce_sels(node, data_mask, context_mask, init = init)
   21.               └─tidyselect:::walk_data_tree(new, data_mask, context_mask)
   22.                 └─tidyselect:::as_indices_sel_impl(...)
   23.                   └─tidyselect:::as_indices_impl(x, vars, call = call, strict = strict)
   24.                     └─tidyselect:::chr_as_locations(x, vars, call = call)
   25.                       └─vctrs::vec_as_location(x, n = length(vars), names = vars)
   26.                         └─vctrs (local) `<fn>`()
   27.                           └─vctrs:::stop_subscript_oob(...)
   28.                             └─vctrs:::stop_subscript(...)
   29.                               └─rlang::abort(...)
  Execution halted
```

**Comment by eutwt** [comment]
I think the column "fad_mean" it's looking for [when the error occurs](https://github.com/hunter-stanke/rFIA/blob/27ef29d2ded3e60a43c2ff227149499b618339ba/R/area_new.R#L393) is the one actually named "fad_mean_mean" in the input table. It's called that because `across` adds "_mean" to the end of the variable being summarised [here](https://github.com/hunter-stanke/rFIA/blob/27ef29d2ded3e60a43c2ff227149499b618339ba/R/functionsFIA.R#L2751), and the variable being summarised already has ["_mean" as part of the name](https://github.com/hunter-stanke/rFIA/blob/27ef29d2ded3e60a43c2ff227149499b618339ba/R/functionsFIA.R#L2717). It doesn't seem related to dtplyr, but I also can't really make sense of why that error would be there when, from what I can tell, all that same code was there when it was loaded to CRAN, according to [CRAN mirror](https://github.com/cran/rFIA/blob/master/R/area_new.R)

**Comment by eutwt** [comment]
Actually, it looks like dtplyr does not handle the naming of `across` output columns correctly, and rFIA is relying on dtplyr behavior.
``` r
devtools::load_all('~/Documents/GitHub/dtplyr/')
#> ℹ Loading dtplyr
#> Warning: package 'dplyr' was built under R version 4.1.2

data.frame(a_mean = 1) %>% 
  lazy_dt() %>% 
  summarise(across(a_mean, list(mean = mean)))
#> Source: local data table [1 x 1]
#> Call:   `_DT1`[, .(a_mean = mean(a_mean))]
#> 
#>   a_mean
#>    <dbl>
#> 1      1
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results

data.frame(a_mean = 1) %>% 
  summarise(across(a_mean, list(mean = mean)))
#>   a_mean_mean
#> 1           1
```

<sup>Created on 2022-07-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by markfairbanks** [comment]
> Actually, it looks like dtplyr does not handle the naming of across output columns correctly

dtplyr matches dplyr now in the dev version.

``` r
devtools::load_all(".")
#> ℹ Loading dtplyr

data.frame(a_mean = 1) %>%
  lazy_dt() %>% 
  summarise(across(a_mean, list(mean = mean)))
#> Source: local data table [1 x 1]
#> Call:   `_DT1`[, .(a_mean_mean = mean(a_mean))]
#> 
#>   a_mean_mean
#>         <dbl>
#> 1           1
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
```

So that's causing the failure.

**Comment by markfairbanks** [comment]
So in the CRAN version - naming was incorrect if you provided a list of length == 1, but was correct if you provided a list of length > 1 🤷‍♂️ 

``` r
library(dtplyr)
library(dplyr, w = FALSE)

df <- lazy_dt(data.frame(a_mean = 1))

df %>%
  summarize(across(a_mean, list(mean = mean)))
#> Source: local data table [1 x 1]
#> Call:   `_DT1`[, .(a_mean = mean(a_mean))]
#> 
#>   a_mean
#>    <dbl>
#> 1      1
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results

df %>%
  summarise(across(a_mean, list(mean = mean, sum = sum)))
#> Source: local data table [1 x 2]
#> Call:   `_DT1`[, .(a_mean_mean = mean(a_mean), a_mean_sum = sum(a_mean))]
#> 
#>   a_mean_mean a_mean_sum
#>         <dbl>      <dbl>
#> 1           1          1
#> 
#> # Use as.data.table()/as.data.frame()/as_tibble() to access results
```

**Comment by hadley** [comment]
Ok, so I think this is good to merge, and we'll just be sure to release after dplyr, and probably make it a major version of dtplyr.

**Comment by markfairbanks** [comment]
Sounds good

**Comment by markfairbanks** [comment]
Any idea what's going on with this failed check? Can that be ignored for now?

**Pull request merged**
